import "./globals.css";
import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";

const manrope = Manrope({ subsets: ["latin-ext"], variable: "--font-manrope" });
const playfair_display = Playfair_Display({
	subsets: ["latin-ext"],
	variable: "--font-playfair-display",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${manrope.variable} ${playfair_display.variable}`}>{children}</body>
		</html>
	);
}
